[package]
name = "qsdr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
futures = "0.3.31"
libc = "0.2.159"
pin-project-lite = "0.2.15"
qsdr-macros = { path = "../qsdr-macros" }

[dev-dependencies]
rand = "0.8.5"
